remote_theme: rundocs/jekyll-rtd-theme
name: Palīdzība programmēšanā
license:
  software: MIT License
  software_url: http://opensource.org/licenses/MIT

  docs: CC BY 3.0
  docs_url: http://creativecommons.org/licenses/by/3.0/
links:
  header:
    - title: GitHub
      url: https://github.com/kristapsmu/progr
plugins:
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-mentions